CREATE TABLE IF NOT EXISTS revinfo
(
  id             INTEGER GENERATED BY DEFAULT
    AS IDENTITY ( START WITH 1 ),
  timestamp        BIGINT,
  user_agent      TEXT,
  accept_language TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vets
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE IF NOT EXISTS vets_aud
(
  id         BIGINT                           NOT NULL,
  rev        INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype    INT,
  revend     INTEGER REFERENCES revinfo (id),
  first_name text,
  last_name  text,
  PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS specialties
(
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS specialties_aud
(
  id        BIGINT                           NOT NULL,
  rev       INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype   INT,
  revend    INTEGER REFERENCES revinfo (id),
  name      text,
  last_name text,
  PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS vet_specialties
(
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types
(
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);


CREATE TABLE IF NOT EXISTS types
(
  id      BIGINT                           NOT NULL,
  rev     INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype INT,
  revend  INTEGER REFERENCES revinfo (id),
  name    TEXT,
  PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS owners
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON owners (last_name);

CREATE TABLE IF NOT EXISTS owners_aud
(
  id         BIGINT                           NOT NULL,
  rev        INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype    INT,
  revend     INTEGER REFERENCES revinfo (id),
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  telephone  TEXT,
  PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS pets
(
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);

CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE IF NOT EXISTS pets_aud
(
  id         BIGINT                           NOT NULL,
  rev        INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype    INT,
  revend     INTEGER REFERENCES revinfo (id),
  name       TEXT,
  birth_date DATE,
  type_id    INT,
  owner_id   INT,
  PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS visits
(
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);


CREATE TABLE IF NOT EXISTS visits_aud
(
  id          BIGINT                           NOT NULL,
  rev         INTEGER REFERENCES revinfo (id) NOT NULL,
  revtype     INT,
  revend      INTEGER REFERENCES revinfo (id),
  pet_id      INT,
  visit_date  DATE,
  description TEXT,
  PRIMARY KEY (id, rev)
);
